### ISSUE TITLE
Enhancement: Add SEO parameters to theme

### ISSUE THREAD

**Issue by dudil** [jpescador/hugo-future-imperfect#113]
## Expected Behavior

I suggest an improvement to implement SEO code to websites.
The implementation is following the description in the following blog:
[https://keithpblog.org/post/hugo-website-seo/](https://keithpblog.org/post/hugo-website-seo/)
I've implemented the changes on my own site and they are working fine and easy to set.
I'll be happy to submit a PR if relevant to the general public

## Current Behavior

The SEO parameter do not implemented today in theme and needed to be added manually.

## Possible Solution

If not implemented on theme level, one could follow the instructions above to set it manually.

## Steps to Reproduce or Template with Error (for bugs)

N/A

## Context

I was trying to push my site via the search engines and was looking for the right way to do so on Hugo
## Your Environment

**Hugo Version:**
0.35

**Browser:**
OSX/iOS Safari

**Desktop or Mobile:**
Both

**Link to your project:**
[https://elv8.co](https://elv8.co)

**Comment by pacollins** [comment]
I do think that this is something that would be worthwhile for the theme. The majority of people will be looking for this (I assume). As long as its easy to customize for the user, I'd say go ahead and throw the PR up unless someone else has something on the topic.

**Comment by dudil** [comment]
@pacollins - sure I'll do it and add the relevant instructions and links to the readme file
