### ISSUE TITLE
Issue\Bug: h1 element font-size is not set on the main.css file

### ISSUE THREAD

**Issue by dudil** [jpescador/hugo-future-imperfect#114]
## Expected Behavior

h1 post headers should be slightly bigger than h2 headers on posts

## Current Behavior

I'm not sure if intended but currently h1 is slightly smaller than h2 headers on posts. The reason for that is that h1 don't-size property is not set under the main.css theme file

## Possible Solution

Add h1 property to the css file (after line 212).
``` CSS
h1 {
        font-size: 1.3em;
 }
```
- **if this is proper solution I will  be happy to assist with PR**

## Steps to Reproduce or Template with Error (for bugs)

1. Create markdown file with 3 headers, h1 (#), h2(##) h3(###)
2. Generate website preview, you should notice h2 is little bigger than h1

## Context

It is making the post to look weird when using both headers

## Your Environment

**Hugo Version:**
0.35

**Browser:**
Safari OSx/iOS

**Desktop or Mobile:**
Both

**Link to your project:**
https://elv8.co

**Comment by pacollins** [comment]
Thanks for catching this. In the grand scheme of the theme, we are hoping to rebase the CSS to remove the clutter that comes from original theme. If you are interested in helping with that, let me know. If I can find the original post that addresses it, I'll link it.

**Comment by dudil** [comment]
@pacollins - Sure I'll be happy to assist.
Let me know how.
