### ISSUE TITLE
Invalid tag closed

### ISSUE THREAD

**Issue by peaceiris** [jpescador/hugo-future-imperfect#118]
## Steps to Reproduce or Template with Error (for bugs)

1.
2.
3.
4.

## Context

https://github.com/jpescador/hugo-future-imperfect/blob/b4bd0f35f0431429c9f108542a368274b68b23f4/layouts/partials/sidebar.html#L116

If I understand correctly, what you want to do is that:

```html
<h3>About</h3> 
```

This issue is my first sending in my github life. Forgive me if I'm wrong.

Thank you always for your great work.

## Your Environment

**Hugo Version:**

**Browser:**

**Desktop or Mobile:**

**Link to your project:**
https://www.p-iris.com/

**Comment by pacollins** [comment]
Thanks @peaceiris for this catch and welcome to GitHub! You did everything right! I will push a fix in a bit.
