### ISSUE TITLE
Add mathjax integration

### ISSUE THREAD

**Issue by DanOvando** [jpescador/hugo-future-imperfect#124]
## Expected Behavior

Great theme, thanks! I'm writing an academic blog using [blogdown](https://bookdown.org/yihui/blogdown/) and `hugo-future-imperfect`. Posts usually involve at least a few mathematical equations, so wanted to build that capacity into this theme

## Current Behavior

Equations do not seem to be currently supported, and I couldn't find any reference to equations in the documentation, current issues, or pull requests. So, this will allow users of the theme to easily integrate equations in their blogs. 

## Possible Solution

I simply integrated the steps for integrating mathjax from the `blgodown` [default theme](https://bookdown.org/yihui/blogdown/themes.html). I'm very new to hugo but it works on my end, branch with mathjax integration [here](https://github.com/DanOvando/hugo-future-imperfect/tree/add-mathjax). Should be ready for a pull request if you feel this feature is worth exploring

## Steps to Reproduce or Template with Error (for bugs)

1.
2.
3.
4.

## Context

Sometimes despite our best intentions we're forced to write equations in blogs, hopefully this helps other users accomplish this using your theme

## Your Environment

**Hugo Version:**
0.36
**Browser:**
Firefox

**Desktop or Mobile:**
Desktop
**Link to your project:**
https://github.com/DanOvando/hugo-future-imperfect/tree/add-mathjax

**Comment by DanOvando** [comment]
[mathjax](https://www.mathjax.org/#docs)

**Comment by pacollins** [comment]
Feel free to make the PR and we can review from there.

Thanks for your contribution!
