### ISSUE TITLE
Featured image not appearing in link thumbnail on social media

### ISSUE THREAD

**Issue by skokenes** [jpescador/hugo-future-imperfect#132]
Hi, I am trying to share a post I created with this theme on a social media platform (LinkedIn to be specific). When I copy the URL into a LinkedIn post, the preview image for the URL is blank. I do not have this problem with posts from the example site that you have hosted online, so I figure I must be configuring something wrong? How do I enable preview thumbnails to appear with my blog posts?

**Comment by skokenes** [comment]
Figured it out, issue was unrelated to the theme

**Comment by mbaljeetsingh** [comment]
@skokenes  How did you fix it?

**Comment by HShamilSamsudeen** [comment]
@skokenes how did you fix it?
