### ISSUE TITLE
Questions regarding theme instructions

### ISSUE THREAD

**Issue by zeebluejay** [jpescador/hugo-future-imperfect#14]
Hello @jpescador,

First of all, thank you for creating this theme and make it available. I am experimenting with it right now to create my own blog. After reading Hugo docs and your themes install instructions, I was able to setup a sample site of my own and running it locally. But there are a few things not clear from your instructions, thought I ask you here and perhaps you can adjust the instructions to make them more clear. Note that if these questions sound newbie, then they probably are as this is the first time I am trying out Hugo.
1. I copied the contents of "/Users/zeekay/dev/blog/hugo/myblog/themes/hugo-future-imperfect/exampleSite/static" to "/Users/zeekay/dev/blog/hugo/myblog/static" and my site works locally. But when I copy the static from "/Users/zeekay/dev/blog/hugo/myblog/themes/hugo-future-imperfect/static" to "/Users/zeekay/dev/blog/hugo/myblog/static" then the site breaks. What is the point really to have static content in "/Users/zeekay/dev/blog/hugo/myblog/themes/hugo-future-imperfect/static"?
2. Do I need to copy any content from "archetype", "images" or "layouts" from "/Users/zeekay/dev/blog/hugo/myblog/themes/hugo-future-imperfect/" to my site's root folders respectively? If not, then why are they there?
3. What is the difference between a post and a blog in the context of this theme? They both render the same in my site.
4. The root URL http://localhost:1313/ shows my recent post on the front page. But http://localhost:1313/blog/ shows summary list of posts / blogs. How to I make the default root url to show the summary list instead without redirecting the user?

Thanks
ZeeKay

**Comment by jpescador** [comment]
Issue resolved with #48

**Comment by dstamen** [comment]
what was the resolution for #4 to change the blog to root so its just not showing the recent post?
