### ISSUE TITLE
Having 4 "Uncategorized" posts despite only have one post, and that categorized.

### ISSUE THREAD

**Issue by joshuawallace** [jpescador/hugo-future-imperfect#142]
## Expected Behavior

Just starting out my site.  I copied things over from the exampleSite directory, deleted the four example blog posts, and made one of my own and gave it a categorization.  I would expect based on this that under the "Categories" tab I would just see the one category that's been named so far and "1" next to it.

## Current Behavior

As can be seen in the image though, I also have "Uncategorized       4" listed, and "Uncategorized" isn't linked to anything.
<img width="1275" alt="screen shot 2018-05-29 at 16 39 25" src="https://user-images.githubusercontent.com/5067798/40684721-1a44f4a4-6360-11e8-9960-ab36317166fd.png">

## Your Environment

**Hugo Version:** 0.41

**Browser:** Chrome and Safari

**Desktop or Mobile:** Desktop

**Link to your project:** https://github.com/joshuawallace/jwblog

**Comment by pacollins** [comment]
Its from the itemized posts I do believe. Development has slowed down on this theme as I am working on rebasing it with CSS Grid and update it with modern Hugo functions.  If you have issues, let me know.

**Comment by joshuawallace** [comment]
I confirm.  I deleted the itemized posts and the Categories tab is now only showing the category from my single blog post.

What are the itemized posts supposed to be used for?  I can't tell from the example site.

**Comment by pacollins** [comment]
I used them for different webapps I've created. It's meant to be a way to
create a list of products/creations rather than blog posts. The intent was
a more condense list page.

**Comment by joshuawallace** [comment]
Thanks.
