### ISSUE TITLE
Error: Near line 2 (last key parsed ''): Expected a top-level item to end with a new line, comment or EOF, but got '-' instead.

### ISSUE THREAD

**Issue by jilcimar** [jpescador/hugo-future-imperfect#145]
Estou tentando seguir a documentação e quando executo o comando 4 "Step 4: Add Some Content" 

o comando é esse: "hugo new posts/my-first-post.md" 

e ele me retorna o seguinte erro:

Error: Near line 2 (last key parsed ''): Expected a top-level item to end with a new line, comment or EOF, but got '-' instead.

Estou usando o Linux Mint 18.3

**Comment by ChangChunHe** [comment]
you can refer to https://github.com/gohugoio/hugo/issues/3626
