### ISSUE TITLE
What is the purpose of "link" for itemized?

### ISSUE THREAD

**Issue by johnatasjmo** [jpescador/hugo-future-imperfect#146]
What is the expected behavior of the value `link =` in itemized content type?

**Comment by peaceiris** [comment]
![link](https://user-images.githubusercontent.com/30958501/42447690-b9829132-83b5-11e8-93cf-082319e378ea.jpg)

If you set `linktitle` and `link` at toml like this

```toml
+++
linktitle = "Github"
link = "https://github.com/peaceiris"
+++
```

You will get the link to GitHub.

This is defined at `layouts/itemized/header.html`

```html
{{ if isset .Params "link" }}                                                                                                                                           
  <a href="{{ .Params.link }}" target="_blank">{{ .Params.linktitle }}</a>                                                                                              
{{ end }}
```

**Comment by johnatasjmo** [comment]
Noted. To be added to the Wiki when available.
