### ISSUE TITLE
Replace "post" in html with params

### ISSUE THREAD

**Issue by qwding** [jpescador/hugo-future-imperfect#15]
Hi
  I'd like this theme. But when I use it. I found that some contents are missing.
  I have three folders under /content/ . But in this theme can only show the content under /content/post.
  I have check the source code. And I found like this `where .Site.Pages "Type" "post"`.  You have judge the page type in the code. I think this not very good, because If I have other types, They all can't be show. 
  I think you can't replace "post" with a param, so that we can show other pages by setting param.
thanks

**Comment by pacollins** [comment]
You just need to set the frontmatter for your post to include `type = "post"` for it to exist.
