### ISSUE TITLE
off canvas nav not quite working

### ISSUE THREAD

**Issue by justrjlewis** [jpescador/hugo-future-imperfect#18]
I'm sure it's something that I've done, but I can't suss out why the off-canvas navigation isn't working on my site: [https://co97.justrjlewis.com](https://co97.justrjlewis.com).  I didn't notice any errors...a few warnings, but no errors.

Could you take a look?

**Comment by justrjlewis** [comment]
@jpescador any thoughts?

**Comment by jpescador** [comment]
Issue resolved with #48
