### ISSUE TITLE
feed::rss

### ISSUE THREAD

**Issue by perpi** [jpescador/hugo-future-imperfect#2]
Hey man, really nice work.

Does it have support for [rss](https://gohugo.io/templates/rss/)?

**Comment by jpescador** [comment]
Hi perpi, thank you very much. I appreciate it. It can be added, I'm thinking of placing the rss link before the social media icons. Please see the image below

![image](https://cloud.githubusercontent.com/assets/2810387/13995020/aaf2f2ee-f0e4-11e5-800b-0b55cd7320ca.png)

**Comment by perpi** [comment]
Oh, it looks great.

**Comment by jpescador** [comment]
RSS link has been added to the master branch
