### ISSUE TITLE
categories link broken

### ISSUE THREAD

**Issue by seepa** [jpescador/hugo-future-imperfect#23]
Hi,

the categories link on the bottom of a post page seems to be missing a "/" in the path. When built, the link currently reads `/categoriesmycategory` where it should be `/categories/mycategory`.

The variable `categoryUrl` which is requested [on this line](https://github.com/jpescador/hugo-future-imperfect/blob/2db677fe337a2bab43b776318559f86db9316daf/layouts/post/footer-category.html#L42) seems to be missing that trailing slash.

Not sure if adding the trailing slash or changing the url in `config.toml` for the categories from 

```
[[menu.main]]
    name = "Categories"
    url = "/categories"
```

to

```
[[menu.main]]
    name = "Categories"
    url = "/categories/"
```

is the right thing to do. What do you think?

best,
Patrick

**Comment by jpescador** [comment]
Issue resolved with #48
