### ISSUE TITLE
Issues installing the theme

### ISSUE THREAD

**Issue by glnarayanan** [jpescador/hugo-future-imperfect#28]
While I'm able to clone other themes and use them directly by configuring the config.toml file or using hugo -t option, I'm unable to use _future-imperfect_  using the same steps. For some reason the site's CSS is never rendered. 

This is what I always get when I try to run Hugo using this theme. Is there a setup instruction that we're missing perhaps?

![image](https://cloud.githubusercontent.com/assets/1026290/20233625/85a42452-a897-11e6-93fc-f5be82456e82.png)

**Comment by bubuzzz** [comment]
you have to copy the `exampleSite` inside the theme to the root folder and start from there

**Comment by jpescador** [comment]
Issue resolved with #48
