### ISSUE TITLE
Custom css support

### ISSUE THREAD

**Issue by onrea** [jpescador/hugo-future-imperfect#3]
May you add this snippet to config file:

    [params]
        custom_css = ["path/to/custom.css"]

**Comment by nraboy** [comment]
Created a PR here https://github.com/jpescador/hugo-future-imperfect/pull/6

**Comment by onrea** [comment]
Really thank you; 

And I think it can take _**customJS**_  too!

**Comment by nraboy** [comment]
What benefit would custom JavaScript solve?  I see the benefit of custom CSS, but no benefit in custom JavaScript.  Can you explain why this would be useful?

**Comment by onrea** [comment]
Sorry, I didn't said it's useful! I have already seen it [here](http://squidfunk.github.io/mkdocs-material/customization/#small-tweaks).

**Comment by nraboy** [comment]
Not trying to be mean, but can you please stop linking everyone to external pages?  Please explain via the issue ticket.  Makes it easier for everyone.

Best,

**Comment by onrea** [comment]
Ah, sorry; This issue was about CSS and now it's in queue as a PR.

Thanks for implementing CSS support.

Cheers
Rea Ontaro

**Comment by jpescador** [comment]
Hey Nic, thanks for jumping in. It's much appreciated. Onrea, you can do this already with the following params in the config file: minifiedFilesCSS and minifiedFilesJS. It's original intention was meant for what the name implies, but you can technically set your custom files here. However, I will be changing the names to customCSS and customJS. I will also slightly restructure the logic in addition to the name change. You can use what is currently there in the meantime. Thank you for your suggestion.

**Comment by jpescador** [comment]
Adding customCSS and customJS functionality per commit, aecd316
