### ISSUE TITLE
Blog section does not have text format

### ISSUE THREAD

**Issue by bubuzzz** [jpescador/hugo-future-imperfect#31]
In a particular post, the text format (like bold, italic) works well. However, when going to the blog section on the navigation bar, all the text (except the title) lose the format. Is it on purpose ? How can I change it ? 

![screen shot 2016-12-08 at 11 42 48 am](https://cloud.githubusercontent.com/assets/571736/20992938/862b63d2-bd3b-11e6-8f4d-6fd79722ff0c.png)
![screen shot 2016-12-08 at 11 42 59 am](https://cloud.githubusercontent.com/assets/571736/20992939/862c1d18-bd3b-11e6-82a7-d881b6b0f9e6.png)

**Comment by pacollins** [comment]
I think this is as intended, but if we could fix it, I think it would be preferable.
