### ISSUE TITLE
Categories at footer not working properly

### ISSUE THREAD

**Issue by vikas-0** [jpescador/hugo-future-imperfect#34]
When clicking on categories on footer it shows 404. The wrong URL is being displayed there. 
For example, on this page, http://themes.gohugo.io/theme/future-imperfect/ try clicking the link of categories on post's footer.

**Comment by joshkestenberg** [comment]
https://github.com/jpescador/hugo-future-imperfect/pull/24 this fixes it.

**Comment by klud1** [comment]
I recently (today) cloned this repo and `categories` isn't working at all, just get `404` pages, been testing the troubleshootings, but nothing seems to work.

**Comment by jpescador** [comment]
Issue resolved with #48
