### ISSUE TITLE
MultiAuthor

### ISSUE THREAD

**Issue by onrea** [jpescador/hugo-future-imperfect#5]
May you add this feature natively: https://discuss.gohugo.io/t/2969

**Comment by nraboy** [comment]
@onrea,

Are you saying you want the following post author to be changed on a per post basis?:

<img width="899" alt="screen shot 2016-03-25 at 10 48 51 am" src="https://cloud.githubusercontent.com/assets/983958/14050163/435f16f0-f277-11e5-9742-0c2489f29b21.png">

Or are you saying you want the core site info author to change?:

<img width="409" alt="screen shot 2016-03-25 at 10 48 57 am" src="https://cloud.githubusercontent.com/assets/983958/14050170/51a091e4-f277-11e5-9838-bbd8a2d78c21.png">

I think it would make more sense for the post author to change, but not the site owner.  It can easily be done by adding front matter to the content after making room for it in the theme.

Is this what you're referring to?  Your issue tickets have hardly any information in them.  It is difficult to read your mind here.

Best,

**Comment by nraboy** [comment]
I take that back, it looks like it was already added:

https://github.com/jpescador/hugo-future-imperfect/blob/master/exampleSite/content/blog/creating-a-new-theme.md#L2

By adding `author` to the front-matter, it will set the post author.

https://github.com/jpescador/hugo-future-imperfect/blob/master/layouts/post/header.html#L23

Without getting sufficient information, we don't know what you're looking for.

Best,

**Comment by onrea** [comment]
> Are you saying you want the following post author to be changed on a per post basis?:

Yours is also another approach. 

but mine is here by more details: Adding a feature to add the author of each post (e.g.) under the title/date of the post. We can use the below part as a part for the website, filling by a logo, etc:

![img](https://cloud.githubusercontent.com/assets/983958/14050170/51a091e4-f277-11e5-9838-bbd8a2d78c21.png)

The current structure is great for a personal website; But with MultiUser feature we can run something like: [LifeHacker](http://lifehacker.com/)

**Comment by nraboy** [comment]
@onrea,

I don't have the slightest idea what you're talking about.  Can you try to be more clear in your comments?

It might be best if you create a pull request with these changes if we can't figure out what you're trying to tell us.

Regards,

**Comment by onrea** [comment]
Oh, Sht; It already [has been implemented](https://github.com/jpescador/hugo-future-imperfect/blob/master/archetypes/blog.md)! I'm really sorry for taking your time;

I run it without '_exampleSite_'. Now I tried `/exampleSite` and I see the author can be changed post to post.
