### ISSUE TITLE
Question: Title on the left of the post

### ISSUE THREAD

**Issue by kerry** [jpescador/hugo-future-imperfect#55]
Which setting do I change to get the title and other things on the left hand side of the post like below?

https://raw.githubusercontent.com/jpescador/hugo-future-imperfect/master/images/screenshot.png

Currently it is like below:

<img width="1268" alt="screen shot 2017-10-04 at 9 01 49 am" src="https://user-images.githubusercontent.com/8803547/31158903-b645204c-a8e2-11e7-8a4c-729b28b634e0.png">

**Comment by pacollins** [comment]
Error in the current repo (my fault), waiting on @jpescador to become active again, or give me contributor access so I can fix it. If you'd like, check out pacollins/hugo-future-imperfect for the most recent version.

**Comment by jpescador** [comment]
@pacollins, boom you are now a collaborator ;)

**Comment by kerry** [comment]
@pacollins I tried your repo's master version but it still does not look like below

![screenshot](https://user-images.githubusercontent.com/8803547/31477256-a9ce2808-af28-11e7-82df-76da03305d35.png)

**Comment by pacollins** [comment]
@kerry, it should as I just tested it. Try clearing files from your browser history.

**Comment by kerry** [comment]
@pacollins Thanks for your response. Will it be possible for you to provide me the dummy website that you just tested? It will save a lot of back and forth

**Comment by pacollins** [comment]
https://imgur.com/a/CmrC0

pacollins.com

**Comment by kerry** [comment]
Thanks @pacollins

**Comment by pacollins** [comment]
@kerry Did that clear it up? Haha I'm happy to help!

**Comment by kerry** [comment]
@pacollins I am trying it again. Will keep you posted. Thanks for the help

**Comment by pacollins** [comment]
@kerry Was this resolved?

**Comment by kerry** [comment]
@pacollins yes. the problem was that when the laptop screen is 1280 px, it has the layout where in the title is on top and on screen bigger than that, the layout is where title is on left. 

I wanted it to be on left on all laptop screens and only switch to the other layout when the width of screen is less than 968px. I will try to modify that myself.

Thanks

**Comment by pacollins** [comment]
You would need to change all the break points in the CSS. I will look into possibility changing this as 1280px seems like a wide break point for that part of the site design, but until then I will close this issue.

**Comment by balldarrens** [comment]
@pacollins - this would be great to fix, or have the ability to simply force '2 column' layout.

**Comment by pacollins** [comment]
@balldarrens - I'm fine with this being adjust, I just don't have the time myself to do it. I believe @BernCarney is looking into cleaning all of the css.

**Comment by balldarrens** [comment]
@BernCarney - are you able to adjust this?

**Comment by BernCarney** [comment]
Sorry I’ve been super busy moving my girlfriend into my place. I’ll take a
look at it this evening or sometime this week.

**Comment by BernCarney** [comment]
Shouldn’t be too bad of a fix, I’ll start working on it if you want to assign it to me.

**Comment by BernCarney** [comment]
@balldarrrens @pacollins started looking into it. 

As a sidenote, this is one of the reason I think the CSS needs a major look at:
![image](https://user-images.githubusercontent.com/18447002/33816722-2f473788-ddf8-11e7-9f26-bca538fb3f32.png)

The font size is being set at _14pt_ but using media queries it is effectively always _12pt_. Lots of unneeded code...

Seems like it was built from a SASS/LESS source so that it could be customized more easily but when porting the theme we're just going off of the output of that.

**Comment by pacollins** [comment]
Don't worry about the timing. We all know everyone is busy and this is a volunteer project. haha
