### ISSUE TITLE
Not able to see disqus comments

### ISSUE THREAD

**Issue by sahil87** [jpescador/hugo-future-imperfect#68]
# Feature or Expected Behavior
After adding disqusShortname to config.toml I expect the disqus comments to show up.

# Current Behavior
Disqus comments not showing up. Neither on localhost nor on live website.

The following change fixes this behaviour: https://github.com/sahil87/hugo-future-imperfect/commit/0996de26b6b2c06401fc4da7c76ed5abc3661b03

I want to know if I am missing something, or if this was intended. If not, would be happy to submit this PR.

**Comment by pacollins** [comment]
Thanks for pointing this out. I had fixed this, but it must have been in one of the commits I reverted. The fix you made to `content-single` is correct, so I'd love it if you made a PR.

You shouldn't need to edit `comments.html` that being said, I'm not sure why `{{ if not (in (printf "%#v" .Site.BaseURL) "localhost") }}` was implemented unless it was an older version of Hugo thing. It's just saying to not print Disqus unless its anything but localhost.

**Comment by sahil87** [comment]
Not removing `{{ if not (in (printf "%#v" .Site.BaseURL) "localhost") }}` prevents disqus from working.

Even in localhost disqus says: `Disqus comments not available by default when the website is previewed locally. comments powered by Disqus`. This message disappears if the above condition exists. Hence, removed the condition.

Created PR https://github.com/jpescador/hugo-future-imperfect/pull/69

**Comment by pacollins** [comment]
I understand what you are saying now. Hugo has it built in to notify you that Disqus doesn't work locally, but that snippet just killed Disqus. I have requested changes on your PR. Thanks for this catch though!

**Comment by pacollins** [comment]
Solved with PR #69 .
