### ISSUE TITLE
Light code block

### ISSUE THREAD

**Issue by radu-matei** [jpescador/hugo-future-imperfect#87]
By default, when I add a code block it has a dark background. 

[In the example site](https://themes.gohugo.io/theme/future-imperfect/) there is a code sample that has a light background - however, I couldn't find any setting regarding this.

Thanks!

**Comment by pacollins** [comment]
Do you have a link to a project or at least an image? I don't seem to be able to create this issue.

**Comment by pacollins** [comment]
Do you still have this issue? Can you give more information? If you have the most recent version of the theme it should match exactly the example site.

**Comment by pacollins** [comment]
This issue is closed due to inactivity. Please feel free to reopen with more information.
