### ISSUE TITLE
li break ol and in header <p> break parent

### ISSUE THREAD

**Issue by alexliyu7352** [jpescador/hugo-future-imperfect#89]
if have long string in header, the <p> will break the parent.
in content div, the li will break ol.
I have fixed this issues, please see
[a3a77b4e79952b7dc73816ed4ee25e712fbfb46d](https://github.com/alexliyu7352/hugo-future-imperfect/commit/a3a77b4e79952b7dc73816ed4ee25e712fbfb46d)

**Comment by pacollins** [comment]
Please resubmit with the issue template or make a pull request if it is a fix you created. I need more information to understand what you are saying.
