### ISSUE TITLE
uglyurls Hugo setting breaks build process

### ISSUE THREAD

**Issue by zhirschtritt** [jpescador/hugo-future-imperfect#90]
- [x] I am running the latest version of [Hugo](https://github.com/gohugoio/hugo/releases) 
- [x] I am using the latest version of [Hugo-Future-Imperfect](https://github.com/jpescador/hugo-future-imperfect/releases) 
- [x] I checked the [documentation](https://github.com/jpescador/hugo-future-imperfect/wiki) and found no 
- [x] I checked the [issues](https://github.com/jpescador/hugo-future-imperfect/issues?utf8=%E2%9C%93&q=is%3Aissue) to make sure that this issue has not already been filed 

## Expected Behavior
With the `uglyurls` set to `true` in config.toml, url links should have index.html appended to them. 

## Current Behavior
When `uglyurls` set to `true`, no html files are written for Blog, About, etc. 

Expected: 
```
public/
  ...
  contact/
    index.html
    index.xml
  ...  
```

Current:
```
public/
  ...
  contact/
    index.xml
  ...  
```

## Possible Solution
One solution is to simply disregard this feature, which is actually quite reasonable since "ugly urls" aren't required for most setups. 

## Steps to Reproduce or Template with Error (for bugs)
1. Create new hugo site:  `hugo new site testsite`
2. Clone down hugo-future-imperfect and copy examplesite data to root: `git clone https://github.com/jpescador/hugo-future-imperfect.git themes/ && cp -a themes/hugo-future-imperfect/exampleSite/content ./`
3. Copy config.toml file to root: `cp themes/hugo-future-imperfect/exampleSite/config.toml ./`
4. Set tag `uglyurls = true` in config.toml
5. Build `hugo -v`

## Your Environment
Hosting on AWS S3 with Cloudfront requires that files end in index.html. I've tried a number of workarounds but no success. 

**Hugo Version:**
v0.30.2 

**Browser:**
Chrome v62 - macos

**Desktop or Mobile:**
Desktop

**Link to your project:**
[github.com/zhirschtritt/my-website](https://github.com/zhirschtritt/my-website)

**Comment by pacollins** [comment]
I'm guessing that this is a newer feature that just hasn't been accounted for since this theme was built on Hugo ~0.15?

I will read up about `uglyurls` to see what a fix might be.

**Comment by zhirschtritt** [comment]
OK - I found a solution, but it's not great. If I build with `uglyurls = false` first, I can create the `index.html` files, *then* I change `uglyurls = true` and, without removing the previous `public` build, I do another build. So, now I don't have broken links but need a custom build process. Eh.

**Comment by pacollins** [comment]
Have you tried it with another theme?

**Comment by zhirschtritt** [comment]
I just did (with [cocoa](https://github.com/nishanths/cocoa-hugo-theme)) and got the same results, which I don't quite understand. It makes me think I have a configuration error on my machine or I'm fundamentally misunderstanding uglyurls within hugo. I'll try it on another machine later.

**Comment by pacollins** [comment]
Since this isn't directly related to the theme, I recommend you post on the Hugo discussion forum and I will close this discussion.

I hope you figure it out!
