### ISSUE TITLE
Toggle to hide category in sidebar

### ISSUE THREAD

**Issue by ParitoshBh** [jpescador/hugo-future-imperfect#99]
- I am running the latest version of [Hugo](https://github.com/gohugoio/hugo/releases) - Yes
- I am using the latest version of [Hugo-Future-Imperfect](https://github.com/jpescador/hugo-future-imperfect/releases) - Yes
- I checked the [documentation](https://github.com/jpescador/hugo-future-imperfect/wiki) and found no answer - Yes
- I checked the [issues](https://github.com/jpescador/hugo-future-imperfect/issues?utf8=%E2%9C%93&q=is%3Aissue) to make sure that this issue has not already been filed - Yes

## Expected Behavior
An option in `config.toml` something along the lines of `socialAppearAtTop` viz. `displayCategories` which essentially toggles `Categories` section in sidebar.

## Current Behavior
Currently, there isn't a way to hide the `Categories` section in sidebar, unless I overlooked some part of documentation in which case it would be great if someone could point me the right direction.

## Possible Solution
1. Add `displayCategories    = false` to `config.toml`.
2. Wrap this [block](https://github.com/jpescador/hugo-future-imperfect/blob/master/layouts/partials/sidebar.html#L79-L109) in `if` condition using `displayCategories` 

## Context
Aiming to keep the sidebar clean (and less cluttered). I'd rather prefer to dedicate a page to show all available (or most used) categories instead of crowding sidebar. Moreover, it adds a level of flexibility.

**Comment by ParitoshBh** [comment]
I can work on this. Went through the contributing documentation and just to make sure, I need to create a pull request and work on this (after cloning the repo and create a new feature branch). Is that correct?

I am relatively new to community contributions so please let me know if anything was skipped/missed!

**Comment by pacollins** [comment]
Nope, that's about it. If you have any more questions about contributing,
feel free to ask!
